### PR TITLE
bytecode / custom needs -cclib as well

### LINKED ISSUE #115: Custom runtime does not compile on FreeBSD
I'm not sure if it compiles elsewhere but I get:

    /tmp/camlprim076048-c98550.o:(.data+0x1038): undefined reference to `caml_nc_xor_into'
    /tmp/camlprim076048-c98550.o:(.data+0x1040): undefined reference to `caml_nc_sha512_init'
    /tmp/camlprim076048-c98550.o:(.data+0x1048): undefined reference to `caml_nc_sha512_update'
    /tmp/camlprim076048-c98550.o:(.data+0x1050): undefined reference to `caml_nc_sha512_finalize'
    /tmp/camlprim076048-c98550.o:(.data+0x1058): undefined reference to `caml_nc_sha512_ctx_size'
    /tmp/camlprim076048-c98550.o:(.data+0x1060): undefined reference to `caml_nc_sha384_init'
    ...

I would guess this is the same issue as:

https://github.com/dbuenzli/mtime/issues/16

### PR DESCRIPTION
**Pull request by hannesm**
this fixes https://github.com/mirleft/ocaml-nocrypto/issues/115

### CODE REVIEW

**Comment by hannesm** [comment]
also fixes #9

**Comment by copy** [comment]
@pqwy Would you review and possibly merge this? This fixes utop for a many nocrypto users (see https://github.com/mirleft/ocaml-nocrypto/issues/115).

**Comment by mseri** [comment]
Any update on this?

**Comment by hcarty** [comment]
As another data point - this PR fixes custom utop sessions built with libraries such as nocrypto which use ocb-stubblr.  Thank you @hannesm for making it available.

**Comment by mseri** [comment]
@pqwy is it possible to have this reviewed or merged?

**Pull request closed without merging**
